apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app: {{ template "application.fullname" . }}
    chart: {{ template "application.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "application.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "application.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
              name: {{ .Values.container.name }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.container.name }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.container.name }}
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              value: {{ .Values.applicationInsights.InstrumentationKey }}
            {{- $root := . }}
            {{- range $ref, $values := .Values.secrets }}
            {{- range $key, $value := $values }}
            - name: {{ $ref | upper }}_{{ $key | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "application.fullname" $root }}-{{ $ref }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
