apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app: {{ template "application.fullname" . }}
    chart: {{ template "application.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:    
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.environment | lower }}-{{ template "application.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "application.fullname" . }}
    release: {{ .Release.Name }}
	